# PostgreSQL configuration for DiveShopOS
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: vamosabucear_development
  cache:
    <<: *default
    database: vamosabucear_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: vamosabucear_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: vamosabucear_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: vamosabucear_test
  cache:
    <<: *default
    database: vamosabucear_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: vamosabucear_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: vamosabucear_test_cable
    migrations_paths: db/cable_migrate

staging:
  primary:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: <%= ENV.fetch("DB_NAME", "vamosabucear_staging") %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: vamosabucear_staging_cache
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: vamosabucear_staging_queue
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: vamosabucear_staging_cable
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: <%= ENV.fetch("DB_NAME", "vamosabucear_production") %>
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: vamosabucear_production_cache
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: vamosabucear_production_queue
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: vamosabucear_production_cable
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    migrations_paths: db/cable_migrate
